# Generated by Django 4.2.3 on 2023-07-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_image',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='is_image',
            new_name='is_active',
        ),
    ]
