# Generated by Django 4.2.3 on 2024-09-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_testimonial_thumbnail_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill',
            field=models.ManyToManyField(blank=True, to='main.skill'),
        ),
    ]
