# Generated by Django 4.2.3 on 2024-09-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userprofile_skills_userprofile_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='skill',
            new_name='skills',
        ),
    ]
